[package]
name = "stamp-net"
version = "0.1.0"
authors = ["Andrew Danger Lyon <andrew@killtheradio.net>"]
edition = "2021"

[dependencies]
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"
getset = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p", rev = "62622a1bad70381e56237b4da4d9abcf2b1a0e24", features = ["dcutr"] }
rasn = { git = "https://github.com/XAMPPRocky/rasn/", rev = "550a3356851e67c1e2accf2e7ed03aeeacb1b43c" }
stamp-core = { path = "../core" }
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }

