[package]
name = "stamp-net"
version = "0.1.0"
authors = ["Andrew Danger Lyon <andrew@killtheradio.net>"]
edition = "2021"

[dependencies]
async-std = { version = "1.11", features = ["attributes"] }
clap = "3.2.5"
env_logger = "0.9"
futures = "0.3"
libp2p = { version = "0.45", features = ["dcutr"] }
log = "0.4"
stamp-core = { path = "../core" }

